"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowUpRight, ArrowRight, Box, Crosshair, Hexagon, PencilLine, Play, Pause, RotateCcw, Shield, X, Zap, ChevronRight, Radio, Navigation, Volume2, VolumeX } from "lucide-react";
import SpaceScene from "./space-scene";
import SketchPad from "./sketch-pad";
import { FLEET, DURATION, practiceMission, validateMission, type Hull, type Mission } from "@/lib/game/types";
import { createFlight, type Flight, type Input } from "@/lib/game/simulation";
const PRACTICE=practiceMission();
export default function CargoGame(){
 const [hull,setHull]=useState<Hull>(FLEET[0]),[custom,setCustom]=useState<Hull|null>(null),[mission,setMission]=useState<Mission>(PRACTICE),[mode,setMode]=useState<"hangar"|"flight">("hangar"),[run,setRun]=useState(0),[flight,setFlight]=useState<Flight>(()=>createFlight(FLEET[0])),[paused,setPaused]=useState(false),[sketch,setSketch]=useState(false),[aiReady,setAIReady]=useState(false),[loading,setLoading]=useState(false),[notice,setNotice]=useState(""),[graphicsError,setGraphicsError]=useState(""),[muted,setMuted]=useState(false);
 const input=useRef<Input>({x:0,y:0,fire:false}),keys=useRef(new Set<string>()),audio=useRef<AudioContext|null>(null),lastAudio=useRef({shots:0,hits:0,status:"flying"});
 const closeSketch=useCallback(()=>setSketch(false),[]);
 useEffect(()=>{fetch("/api/ai-status").then(r=>r.json()).then(v=>setAIReady((v as {available?:boolean}).available===true)).catch(()=>setAIReady(false));},[]);
 const tone=useCallback((frequency:number,length:number,type:OscillatorType="sine")=>{if(muted||!audio.current)return;const ctx=audio.current;const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(frequency,ctx.currentTime);o.frequency.exponentialRampToValueAtTime(frequency*.4,ctx.currentTime+length);g.gain.setValueAtTime(.045,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+length);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+length);},[muted]);
 const update=useCallback((s:Flight)=>{setFlight(s);if(s.shots>lastAudio.current.shots)tone(680,.08,"triangle");if(s.hits>lastAudio.current.hits)tone(95,.22,"sawtooth");if(s.status==="delivered"&&lastAudio.current.status!=="delivered")tone(880,.6);lastAudio.current={shots:s.shots,hits:s.hits,status:s.status};},[tone]);
 useEffect(()=>{
  function sync(){input.current.x=(keys.current.has("KeyD")||keys.current.has("ArrowRight")?1:0)-(keys.current.has("KeyA")||keys.current.has("ArrowLeft")?1:0);input.current.y=(keys.current.has("KeyW")||keys.current.has("ArrowUp")?1:0)-(keys.current.has("KeyS")||keys.current.has("ArrowDown")?1:0);input.current.fire=keys.current.has("Space");}
  function keydown(e:KeyboardEvent){if(mode!=="flight")return;if(["Space","ArrowUp","ArrowDown","ArrowLeft","ArrowRight"].includes(e.code))e.preventDefault();if(e.code==="Escape"&&!e.repeat)setPaused(p=>!p);keys.current.add(e.code);sync();}
  function keyup(e:KeyboardEvent){keys.current.delete(e.code);sync();}
  function blur(){keys.current.clear();input.current={x:0,y:0,fire:false};if(mode==="flight")setPaused(true);}
  function visibility(){if(document.hidden)blur();}
  window.addEventListener("keydown",keydown);window.addEventListener("keyup",keyup);window.addEventListener("blur",blur);document.addEventListener("visibilitychange",visibility);
  return()=>{window.removeEventListener("keydown",keydown);window.removeEventListener("keyup",keyup);window.removeEventListener("blur",blur);document.removeEventListener("visibilitychange",visibility);};
 },[mode]);
 async function plan(){setLoading(true);setNotice("");try{const res=await fetch("/api/mission",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ship:hull.name}),signal:AbortSignal.timeout(35000)});const data=await res.json() as {error?:string;mission?:unknown};if(!res.ok)throw new Error(data.error||"The director is unavailable.");setMission(validateMission(data.mission));}catch(e){setNotice((e instanceof Error?e.message:"AI director unavailable.")+" Practice route is ready to fly.");setMission(PRACTICE);}finally{setLoading(false);}}
 useEffect(()=>{if(aiReady)void plan();},[aiReady]);
 function launch(){keys.current.clear();input.current={x:0,y:0,fire:false};lastAudio.current={shots:0,hits:0,status:"flying"};setFlight(createFlight(hull));setPaused(false);setRun(r=>r+1);setMode("flight");if(!audio.current)try{audio.current=new AudioContext();}catch{}audio.current?.resume();}
 function hangar(){setMode("hangar");setPaused(false);input.current={x:0,y:0,fire:false};}
 function useCustom(h:Hull){setCustom(h);setHull(h);setSketch(false);setNotice(h.origin==="openai"?"Your OpenAI-designed hull is ready. Preview it, then launch.":"Your local sketch-built hull is ready to fly.");}
 const ended=mode==="flight"&&flight.status!=="flying",delivered=flight.status==="delivered";
 return <main className={`game-shell ${mode==="flight"?"in-flight":"in-hangar"}`}>
  <header className="topbar"><a className="wordmark" href="/" aria-label="Space Race home"><span className="brand-mark"><Hexagon size={29}/><Navigation size={15}/></span><span>SPACE<span className="logo-light">RACE</span></span></a><nav aria-label="Game phases"><span className={mode==="hangar"?"active":""}>01 <b>HANGAR</b></span><ChevronRight size={14}/><span className={mode==="flight"?"active":""}>02 <b>DELIVERY</b></span></nav><div className="header-right"><span className="version-label">CARGO RUN / 01</span><button className="icon-button" aria-label={muted?"Enable sound":"Mute sound"} onClick={()=>setMuted(m=>!m)}>{muted?<VolumeX size={18}/>:<Volume2 size={18}/>}</button></div></header>
  {mode==="hangar"?<>
   <section className="hangar-main"><div className="ship-info"><span className="eyebrow">HANGAR 07 / SELECT VESSEL</span><h1>Ready for <br/>the run.</h1><p className="intro">Get the supplies to Kepler Outpost. <br/>Keep the pirates off your cargo.</p><div className="ship-specs"><div><Shield size={17}/><span>HULL ARMOR</span><b>{hull.armor}</b></div><div><Zap size={17}/><span>HANDLING</span><b>{hull.handling>1?"AGILE":hull.handling<1?"STEADY":"BALANCED"}</b></div><div><Crosshair size={17}/><span>WEAPONS</span><b>PULSE CANNONS</b></div><div><Box size={17}/><span>PAYLOAD</span><b>MEDICAL SUPPLIES</b></div></div><span className="small-note">{hull.origin==="openai"?"OPENAI-DESIGNED HULL":hull.origin==="local"?"LOCAL SKETCH-BUILT HULL":"FLIGHT SYSTEMS READY"}</span></div>
   <div className="hangar-viewport"><span className="viewport-caption"><span className="corner"/> LIVE 3D / {hull.id.toUpperCase()}</span><SpaceScene key={`hangar-${hull.name}`} hull={hull} mission={mission} playing={false} paused={false} input={input} onUpdate={update} onError={setGraphicsError}/><div className="ship-name"><span>{hull.role}</span><h2 style={{color:hull.color}}>{hull.name}</h2><p>READY TO FLY <span>↗</span></p></div></div>
   <aside className="mission-card"><div className="mission-top"><span className="eyebrow">DELIVERY CONTRACT</span><span className="contract-id">#KP—001</span></div><h2>The Kepler <br/>passage<span>.</span></h2><div className="route"><div><span className="route-node origin-node"/><span>ORIGIN<b>Port Meridian</b></span></div><div className="route-line"><span>HOSTILE TERRITORY</span></div><div><span className="route-node destination-node"/><span>DESTINATION<b>Kepler Outpost</b></span></div></div><div className="mission-metrics"><div><b>75<span> SEC</span></b><span>FLIGHT TIME</span></div><div><b>100<span> %</span></b><span>LOADED CARGO</span></div></div><div className="threats"><span>EXPECT</span><p>Asteroids · Pirates · Gravity wells</p></div><button className="primary-button" onClick={launch} disabled={loading||!!graphicsError}>Launch delivery <ArrowUpRight size={20}/></button><span className="mission-source"><Radio size={13}/>{mission.source==="openai"?"OpenAI route ready":"Practice route ready"}</span>{aiReady?<button className="quiet-button director-button" onClick={plan} disabled={loading}>{loading?"Director planning encounters…":"Generate an AI route"}</button>:<span className="offline-note">AI director offline · practice available</span>}</aside></section>
   <section className="fleet-section" aria-label="Choose your ship"><div className="fleet-heading"><span className="eyebrow">CHOOSE YOUR SHIP</span><span>03 FLEET VESSELS / {custom?"01":"00"} CUSTOM</span></div><div className="fleet-grid">{FLEET.map((s,i)=><button className={`ship-card ${hull.id===s.id?"selected":""}`} aria-pressed={hull.id===s.id} key={s.id} onClick={()=>setHull(s)} style={{"--ship-color":s.color} as React.CSSProperties}><span className="ship-number">0{i+1}</span><span className="ship-card-name"><b>{s.name}</b><span>{s.role}</span></span><span className="ship-select-icon">{hull.id===s.id?<span className="selected-dot"/>:<ArrowUpRight size={18}/>}</span></button>)}<button className={`ship-card custom-card ${hull.id==="custom"?"selected":""}`} onClick={()=>custom?setHull(custom):setSketch(true)}><PencilLine size={22}/><span className="ship-card-name"><b>{custom?custom.name:"Build your own"}</b><span>{custom?"Your custom 3D hull":"Sketch an optional ship shape"}</span></span><span className="ship-select-icon"><ArrowUpRight size={18}/></span></button></div>{custom&&<button className="quiet-button redraw-button" onClick={()=>setSketch(true)}><PencilLine size={14}/> Draw a new ship</button>}</section>
   {notice&&<p className="notice" role="status">{notice}</p>}
   <footer className="hangar-footer"><span><kbd>W A S D</kbd> / <kbd>↑ ↓ ← →</kbd> STEER</span><span><kbd>SPACE</kbd> FIRE</span><span><kbd>ESC</kbd> PAUSE</span><span className="footer-touch">Touch controls available</span><span className="footer-goal"><Box size={14}/> THE CARGO COMES FIRST.</span></footer>
  </>:<div className="flight-main"><SpaceScene key={run} hull={hull} mission={mission} playing paused={paused||ended} input={input} onUpdate={update} onError={setGraphicsError}/><div className={`damage-flash ${flight.immune>0?"visible":""}`}/><div className="hud-top"><div className="hud-vitals"><div><Shield size={18}/><span>HULL</span><b>{Math.ceil(flight.hull)}<small> / {hull.armor}</small></b><meter min={0} max={hull.armor} value={flight.hull}/></div><div><Box size={18}/><span>CARGO</span><b>{flight.cargo}<small>%</small></b><meter min={0} max={100} value={flight.cargo}/></div></div><div className="route-progress"><div><span>MERIDIAN</span><b>KEPLER OUTPOST</b></div><div className="progress-track"><span style={{width:`${flight.time/DURATION*100}%`}}/></div><span>{Math.ceil(DURATION-flight.time)}s TO DELIVERY · {mission.source==="openai"?"AI ROUTE":"PRACTICE ROUTE"}</span></div><button className="icon-button pause-button" onClick={()=>setPaused(p=>!p)} aria-label="Pause game"><Pause size={20}/></button></div><div className="aim-reticle" aria-hidden="true">+</div><div className="flight-message" role="status"><Radio size={16}/>{flight.warning}</div><div className="flight-bottom"><span><b>{hull.name.toUpperCase()}</b> / FORWARD THRUST ACTIVE</span><span>{flight.kills} TARGETS CLEARED</span></div><div className="touch-controls"><div className="steer-pad" aria-label="Touch steering pad" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);const b=e.currentTarget.getBoundingClientRect();input.current.x=Math.max(-1,Math.min(1,(e.clientX-b.left-b.width/2)/(b.width*.33)));input.current.y=Math.max(-1,Math.min(1,-(e.clientY-b.top-b.height/2)/(b.height*.33)));}} onPointerMove={e=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))return;const b=e.currentTarget.getBoundingClientRect();input.current.x=Math.max(-1,Math.min(1,(e.clientX-b.left-b.width/2)/(b.width*.33)));input.current.y=Math.max(-1,Math.min(1,-(e.clientY-b.top-b.height/2)/(b.height*.33)));}} onPointerUp={()=>{input.current.x=0;input.current.y=0;}} onPointerCancel={()=>{input.current.x=0;input.current.y=0;}}><span>↑</span><div>← <i/> →</div><span>↓</span></div><button className="fire-button" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);input.current.fire=true;}} onPointerUp={()=>input.current.fire=false} onPointerCancel={()=>input.current.fire=false}><Crosshair size={28}/><span>FIRE</span></button></div>
   {(paused||ended)&&<div className="modal-shade"><section className="result-panel"><span className="eyebrow">{ended?delivered?"CONTRACT FULFILLED":"SIGNAL LOST":"FLIGHT ON HOLD"}</span><div className={`result-icon ${delivered?"success":""}`}>{ended?delivered?<Box size={30}/>:<Shield size={30}/>:<Pause size={30}/>}</div><h2>{ended?delivered?"Cargo delivered.":"Shipment lost.":"Take a breath."}</h2><p>{ended?delivered?"Kepler Outpost has received your supplies.":"The route got the better of you. Your next run starts here.":"Your ship and cargo are safe while paused."}</p>{ended&&<div className="result-stats"><div><b>{flight.cargo}%</b><span>CARGO REMAINING</span></div><div><b>{flight.kills}</b><span>TARGETS CLEARED</span></div></div>}<button className="primary-button" onClick={ended?launch:()=>setPaused(false)}>{ended?<RotateCcw size={18}/>:<Play size={18}/>} {ended?"Run it again":"Resume delivery"}</button><button className="quiet-button" onClick={hangar}><ArrowRight size={16}/> Return to hangar</button></section></div>}
  </div>}
  {sketch&&<SketchPad onClose={closeSketch} onUse={useCustom} aiReady={aiReady}/>}
  {graphicsError&&<div className="modal-shade"><section className="result-panel"><h2>Flight systems offline.</h2><p role="alert">{graphicsError}</p><button className="primary-button" onClick={()=>location.reload()}>Reload game <RotateCcw size={18}/></button></section></div>}
 </main>;
}
