"use client";
import { useEffect, useRef, useState } from "react";
import { Eraser, WandSparkles, X, ArrowUp, RotateCcw } from "lucide-react";
import { FLEET, clamp, validateHull, type Hull } from "@/lib/game/types";
export default function SketchPad({onClose,onUse,aiReady}:{onClose:()=>void;onUse:(h:Hull)=>void;aiReady:boolean}){
 const canvas=useRef<HTMLCanvasElement>(null),drawing=useRef(false),points=useRef<{x:number;y:number}[]>([]);
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[hasDrawing,setHasDrawing]=useState(false);
 const reset=()=>{const c=canvas.current,ctx=c?.getContext("2d");if(!c||!ctx)return;ctx.fillStyle="#0b1720";ctx.fillRect(0,0,400,400);points.current=[];setHasDrawing(false);setError("");};
 useEffect(()=>{reset();const escape=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();};window.addEventListener("keydown",escape);return()=>window.removeEventListener("keydown",escape);},[onClose]);
 function draw(e:React.PointerEvent<HTMLCanvasElement>){if(!drawing.current)return;const c=e.currentTarget,box=c.getBoundingClientRect();const p={x:(e.clientX-box.left)*400/box.width,y:(e.clientY-box.top)*400/box.height};const ctx=c.getContext("2d")!;const last=points.current.at(-1);ctx.strokeStyle="#87e5db";ctx.lineWidth=5;ctx.lineCap="round";if(last){ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();}points.current.push(p);setHasDrawing(true);}
 function localHull(){
  const ps=points.current;if(ps.length<12)throw new Error("Draw a larger outline before building your ship.");
  const minY=Math.min(...ps.map(p=>p.y)),maxY=Math.max(...ps.map(p=>p.y)),minX=Math.min(...ps.map(p=>p.x)),maxX=Math.max(...ps.map(p=>p.x));
  if(maxY-minY<60||maxX-minX<30)throw new Error("Give the outline a little more width and length.");
  const center=(minX+maxX)/2;const widths=Array.from({length:9},(_,i)=>{const y=minY+(maxY-minY)*i/8;const near=ps.filter(p=>Math.abs(p.y-y)<(maxY-minY)/12);return clamp(near.length?Math.max(...near.map(p=>Math.abs(p.x-center)))/(maxX-minX)*4:.4,.08,2.2);});
  return {...FLEET[0],id:"custom",name:"Sketch 01",role:"Custom courier",color:"#80e6da",widths,origin:"local" as const};
 }
 async function generate(useAI:boolean){setError("");try{const local=localHull();if(!useAI){onUse(local);return;}setBusy(true);const res=await fetch("/api/ship",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({image:canvas.current!.toDataURL("image/png")}),signal:AbortSignal.timeout(35000)});const data=await res.json() as {error?:string;hull?:unknown};if(!res.ok)throw new Error(data.error||"The ship designer is unavailable.");onUse(validateHull(data.hull));}catch(e){setError(e instanceof Error?e.message:"Could not build the ship.");}finally{setBusy(false);}}
 return <div className="modal-shade"><section role="dialog" aria-modal="true" aria-labelledby="sketch-title" className="sketch-modal"><div className="modal-head"><span className="eyebrow">SHIPYARD / CUSTOM HULL</span><button aria-label="Close ship designer" onClick={onClose} className="icon-button"><X size={20}/></button></div><h2 id="sketch-title">Your outline. Your ship.</h2><p>Sketch the ship from above, nose pointing up. A rough silhouette is enough. We add depth, a cockpit and engines.</p><div className="drawing-wrap"><span className="nose-label"><ArrowUp size={14}/> NOSE</span><canvas ref={canvas} width={400} height={400} aria-label="Draw a top-down spaceship outline" onPointerDown={e=>{drawing.current=true;e.currentTarget.setPointerCapture(e.pointerId);points.current.push({x:(e.clientX-e.currentTarget.getBoundingClientRect().left)*400/e.currentTarget.clientWidth,y:(e.clientY-e.currentTarget.getBoundingClientRect().top)*400/e.currentTarget.clientHeight});}} onPointerMove={draw} onPointerUp={()=>drawing.current=false} onPointerCancel={()=>drawing.current=false}/><span className="draw-hint">Draw with your mouse or finger</span></div><div className="sketch-tools"><button onClick={reset} disabled={busy} className="quiet-button"><Eraser size={16}/> Clear outline</button><span>Mirrored for a balanced hull</span></div>{error&&<p className="error-message" role="alert">{error}</p>}<button className="primary-button" disabled={!hasDrawing||busy} onClick={()=>generate(aiReady)}><WandSparkles size={18}/>{busy?"Building your 3D hull…":aiReady?"Generate ship with OpenAI":"Build local 3D preview"}</button><p className="ai-disclosure">{aiReady?"Your sketch is sent to OpenAI to create a stylized, playable hull.":"AI ship designer offline. The local builder turns your outline into a real 3D hull; it does not use AI."}</p>{error&&aiReady&&<button className="quiet-button" onClick={()=>generate(false)} disabled={busy}><RotateCcw size={16}/> Use local builder instead</button>}</section></div>;
}
