import { aiFailure,generateJSON,readInput } from "@/lib/game/ai";
import { validateMission } from "@/lib/game/types";
export async function POST(request:Request){try{
 await readInput(request);
 const event={type:"object",properties:{at:{type:"number"},kind:{type:"string",enum:["asteroid","pirate","portal"]},x:{type:"number"},y:{type:"number"},count:{type:"integer"}},required:["at","kind","x","y","count"],additionalProperties:false};
 const schema={type:"object",properties:{title:{type:"string"},events:{type:"array",items:event,minItems:24,maxItems:36}},required:["title","events"],additionalProperties:false};
 const result=await generateJSON("cargo_mission",schema,"Direct a fair, exciting 150-second space cargo run from Port Meridian to Kepler Outpost. Return 28 to 34 varied encounters planned before play. Each at is a spawn time in seconds from 4 to 134, sorted with at least 3.5 normal-speed course-seconds between events; they appear 145 units ahead and approach at 29 units/sec, leaving 5 seconds of reaction time. kind asteroid, pirate or portal. Use all three, exactly 2 portals before course coordinate 116 and at least 30 course-seconds apart. Portals are safe optional jump gates which ramp to 3x forward speed for a bounded 8 seconds; at means a route-progress coordinate, not wall-clock time. Warp encounters are spawned further ahead to preserve reaction time. x between -7 and 7, y between -4 and 4. count 1 or 2 for asteroids/pirates, always 1 for portal. Leave clear lateral escape lanes; never wall off the flight corridor x[-9,9] y[-5,5]. Open gently, build to a pirate ambush, include breathers, end with an asteroid escape and a 12-course-second quiet approach to the destination. Choose varied timing/positions each call. Keep only the constrained encounter plan; no code.");
 return Response.json({mission:validateMission(result)},{headers:{"Cache-Control":"no-store"}});
 }catch(e){return aiFailure(e);}}
